###
POST https://syllbuiq-production.up.railway.app/api/auth/add-user
Content-Type: application/json

{
  "name": "hemanth",
  "email": "hemanthramasaia@gmail.com",
  "password": "edrftgyhujik",
  "conformpass": "edrftgyhujik"
}
###
GET https://syllbuiq-production.up.railway.app/api/auth/login-user
Content-Type: application/json

{
  "email": "ramasaiahemanth@gmail.com",
  "password": "hemanth123"
}